### PR TITLE
RegExp can now be used for route options

### PR DESCRIPTION
**Pull request by jdelobel**
## Description

 Allow regular expression for route methods 
example:

` @Get(/\/api-docs\/?.*/))

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by remojansen** [comment]
Awesome :+1: thanks a lot for this contribution. I will try to release it later tonight.

**Comment by jdelobel** [comment]
OK thanks. I wait it

**Comment by remojansen** [comment]
I just release `inversify-restify-utils@3.1.0` :tada: thanks a gain for your PR

**Comment by jdelobel** [comment]
Thanks!  

I forgot the case for:

`  @Get(//api-docs/?.*/)). `

In fact i just made:

`@Get(path: {//api-docs/?.*/})) `

I will do another PR for the first case. :simple_smile:

**Pull request merged**
