### PR TITLE
Remove useless errorConfigFn function

### PR DESCRIPTION
**Pull request by rundef**
So I tested everything, and it's working well.
But the **errorConfigFn** function is useless - error handling is different in restify than in express

### CODE REVIEW

**Comment by remojansen** [comment]
Thanks for the PR! you need to merge https://github.com/rundef/inversify-restify-utils/pull/1 to fix the build before I can merge it.

**Comment by remojansen** [comment]
Merged :tada:

**Comment by remojansen** [comment]
@rundef do we need to update the dts as well? do you need me to do a release?

**Comment by rundef** [comment]
Yes, I'll update the dts later, but no need for a new release.

**Comment by remojansen** [comment]
Thanks!

**Pull request merged**
